apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo
  labels:
    app: nodejs-mongo
spec:
  selector:
    matchLabels:
      app: nodejs-mongo
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs-mongo
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim