apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs-mongo
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    app: nodejs-mongo
    tier: frontend
