kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Values.networkpolicy.deny.name}}
  namespace: {{.Values.networkpolicy.deny.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.app.name}}
      tier: {{.Values.mongo.tier}}
  ingress: []
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{.Values.networkpolicy.allow.name}}
  namespace: {{.Values.networkpolicy.allow.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.app.name}}
      tier: {{.Values.mongo.tier}}
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: {{.Values.app.name}}
          tier: {{.Values.nodejs.tier}}