apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  accessModes:
    - {{.Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{.Values.pvc.storage}}