apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo.service.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  ports:
    - port: {{.Values.mongo.service.port}}
  selector:
    app: {{.Values.app.name}}
    tier: {{.Values.mongo.tier}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nodejs.service.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  type: {{.Values.nodejs.service.type}}
  ports:
    - port: {{.Values.nodejs.service.port}}
      targetPort: {{.Values.nodejs.service.targetport}}
      nodePort: {{.Values.nodejs.service.nodeport}}
  selector:
    app: {{.Values.app.name}}
    tier: {{.Values.nodejs.tier}}